
from django.forms import ModelForm, ValidationError
from crispy_forms.bootstrap import Field, InlineRadios, TabHolder, Tab, InlineCheckboxes
from crispy_forms.layout import Submit, Layout, Div, Fieldset
from crispy_forms.helper import FormHelper
from .models import Advertisement


class GenericImageSize():
    def clean_image1(self):
        image = self.cleaned_data.get('image1', False)
        if image:
            if image._size > 4*1024*1024:
                raise ValidationError("Image file too large ( > 4mb )")
            return image
        else:
            raise ValidationError("Couldn't read uploaded image")

    def clean_image2(self):
        image = self.cleaned_data.get('image2', False)
        if image:
            if image._size > 4*1024*1024:
                raise ValidationError("Image file too large ( > 4mb )")
            return image
        else:
            raise ValidationError("Couldn't read uploaded image")

    def clean_image3(self):
        image = self.cleaned_data.get('image3', False)
        if image:
            if image._size > 4*1024*1024:
                raise ValidationError("Image file too large ( > 4mb )")
            return image
        else:
            raise ValidationError("Couldn't read uploaded image")


class RentApartment(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "deposit",
                "rent",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "water_cooler",
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address",
            "description",
            "year_of_construction",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "telephone_lines",
            "floor_number",
            "exposure_direction",
            "deposit",
            "rent",
            "toilet_type",
            "building_view",
            "cabinet_type",
            "building_status",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "sauna",
            "jacuzzi",
            "swimming_pool",
            "balcony",
            "kitchen",
            "lobby",
            "video_door_phone",
            "remote",
            "table_gas",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "floor_number",
            "deposit",
            "rent",
            "telephone_lines",
            "description",
            "image1",
            "image2",
            "image3",
        }


class SellBuyApartment(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "price",
                "price_square",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "water_cooler",
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "year_of_construction",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "price",
            "price_square",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "exposure_direction",
            "bill_status",
            "density",
            "toilet_type",
            "building_view",
            "cabinet_type",
            "building_status",
            "parking",
            "elevator",
            "depot",
            "sauna",
            "jacuzzi",
            "swimming_pool",
            "balcony",
            "kitchen",
            "lobby",
            "video_door_phone",
            "remote",
            "table_gas",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "image1",
            "image2",
            "image3",
            )
        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "floor_number",
            "price",
            "price_square",
            "description",
            "image1",
            "image2",
            "image3",
        }


class RentEdari(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "deposit",
                "rent",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "water_cooler",
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "telephone_lines",
            "exposure_direction",
            "deposit",
            "rent",
            "toilet_type",
            "telephone_lines",
            "building_view",
            "cabinet_type",
            "building_status",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "video_door_phone",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "floor_number",
            "deposit",
            "rent",
            "telephone_lines",
            "description",
            "image1",
            "image2",
            "image3",
        }


class SellBuyEdari(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True


        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "price",
                "price_square",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "video_door_phone",
                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "price",
            "price_square",
            "exposure_direction",
            "toilet_type",
            "telephone_lines",
            "building_view",
            "cabinet_type",
            "building_status",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "video_door_phone",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "floor_number",
            "telephone_lines",
            "price",
            "price_square",
            "description",
            "image1",
            "image2",
            "image3",
        }


class RentColangi(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "deposit",
                "rent",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "yard",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "water_cooler",
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "year_of_construction",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "telephone_lines",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "yard",
            "exposure_direction",
            "deposit",
            "rent",
            "toilet_type",
            "building_view",
            "building_status",
            "cabinet_type",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "video_door_phone",
            "remote",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "image1",
            "image2",
            "image3",
            )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "floor_number",
            "deposit",
            "rent",
            "telephone_lines",
            "description",
            "image1",
            "image2",
            "image3",
        }


class SellBuyColangi(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "price",
                "price_square",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "yard",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "water_cooler",
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "year_of_construction",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "floor_number",
            "telephone_lines",
            "floors",
            "blocks_per_floor",
            "yard",
            "exposure_direction",
            "price",
            "price_square",
            "toilet_type",
            "building_view",
            "building_status",
            "cabinet_type",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "video_door_phone",
            "remote",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "image1",
            "image2",
            "image3",
            )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "floor_number",
            "telephone_lines",
            "price",
            "price_square",
            "description",
            "image1",
            "image2",
            "image3",
        }


class RentSuit(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "deposit",
                "rent",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "yard",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "water_cooler",
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "description",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "urban_area_number",
            "city",
            "year_of_construction",
            "telephone_lines",
            "room_number",
            "house_square",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "exposure_direction",
            "deposit",
            "rent",
            "toilet_type",
            "building_view",
            "cabinet_type",
            "building_status",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "sauna",
            "jacuzzi",
            "swimming_pool",
            "balcony",
            "kitchen",
            "lobby",
            "video_door_phone",
            "remote",
            "table_gas",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "floor_number",
            "deposit",
            "rent",
            "telephone_lines",
            "description",
            "image1",
            "image2",
            "image3",
        }


class SellBuySuit(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True


        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "price",
                "price_square",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "yard",
                "bill_status",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "water_cooler",
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "description",
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "urban_area_number",
            "city",
            "year_of_construction",
            "telephone_lines",
            "room_number",
            "house_square",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "exposure_direction",
            "price",
            "price_square",
            "bill_status",
            "toilet_type",
            "building_view",
            "cabinet_type",
            "building_status",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "sauna",
            "jacuzzi",
            "swimming_pool",
            "balcony",
            "kitchen",
            "lobby",
            "video_door_phone",
            "remote",
            "table_gas",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "floor_number",
            "telephone_lines",
            "price",
            "price_square",
            "description",
            "image1",
            "image2",
            "image3",
        }


class RentVila(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "deposit",
                "rent",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "yard",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                "caretaker_house",
                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "water_cooler",
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "urban_area_number",
            "city",
            "year_of_construction",
            "room_number",
            "house_square",
            "floors",
            "yard",
            "exposure_direction",
            "deposit",
            "rent",
            "toilet_type",
            "building_view",
            "building_status",
            "cabinet_type",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "sauna",
            "jacuzzi",
            "swimming_pool",
            "balcony",
            "kitchen",
            "lobby",
            "video_door_phone",
            "remote",
            "janitor",
            "table_gas",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "car_door",
            "caretaker_house",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "deposit",
            "rent",
            "description",
            "image1",
            "image2",
            "image3",
        }


class SellBuyVila(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "price",
                "price_square",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "yard",
                "bill_status",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                "caretaker_house",

                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "water_cooler",
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "description",
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "urban_area_number",
            "city",
            "year_of_construction",
            "telephone_lines",
            "room_number",
            "house_square",
            "floors",
            "yard",
            "exposure_direction",
            "price",
            "price_square",
            "bill_status",
            "toilet_type",
            "building_view",
            "building_status",
            "cabinet_type",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "sauna",
            "jacuzzi",
            "swimming_pool",
            "balcony",
            "kitchen",
            "lobby",
            "video_door_phone",
            "remote",
            "janitor",
            "table_gas",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "car_door",
            "caretaker_house",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "price",
            "price_square",
            "description",
            "image1",
            "image2",
            "image3",
        }


class RentTejari(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "deposit",
                "rent",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "category",
                "yard",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "water_cooler",
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "urban_area_number",
            "city",
            "year_of_construction",
            "room_number",
            "house_square",
            "category",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "yard",
            "exposure_direction",
            "deposit",
            "rent",
            "toilet_type",
            "telephone_lines",
            "building_view",
            "building_status",
            "cabinet_type",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "sauna",
            "jacuzzi",
            "swimming_pool",
            "balcony",
            "kitchen",
            "lobby",
            "video_door_phone",
            "remote",
            "janitor",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "floor_number",
            "deposit",
            "rent",
            "telephone_lines",
            "description",
            "image1",
            "image2",
            "image3",
        }


class SellBuyTejari(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "price",
                "price_square",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "category",
                "yard",
                "bill_status",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                ),
           Fieldset('تجهیزات گرمایشی/سرمایشی',
                     "water_cooler",
                     "air_conditioners",
                     "chiller",
                     "duct_split",
                     "package",
                     "radiant",
                     "heater",
                     "floor_heating",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "urban_area_number",
            "city",
            "year_of_construction",
            "room_number",
            "house_square",
            "category",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "yard",
            "exposure_direction",
            "price",
            "price_square",
            "bill_status",
            "toilet_type",
            "telephone_lines",
            "building_view",
            "building_status",
            "cabinet_type",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "sauna",
            "jacuzzi",
            "swimming_pool",
            "balcony",
            "kitchen",
            "lobby",
            "video_door_phone",
            "remote",
            "janitor",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "floor_number",
            "telephone_lines",
            "price",
            "price_square",
            "description",
            "image1",
            "image2",
            "image3",
        }


class RentZamin(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "deposit",
                "rent",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "category",
                "yard",
                "length",
                "water_quota",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                "water",
                "electricity",
                "gas",
                "water_well",
                "car_door",
                "asphalt",
                "caretaker_house",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "building_status",
            "house_square",
            "yard",
            "deposit",
            "rent",
            "length",
            "water_quota",
            "swimming_pool",
            "video_door_phone",
            "janitor",
            "water",
            "electricity",
            "gas",
            "water_well",
            "car_door",
            "asphalt",
            "caretaker_house",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "deposit",
            "rent",
            "description",
            "image1",
            "image2",
            "image3",
        }


class SellBuyZamin(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "price",
                "price_square",
                "bill_status",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "category",
                "yard",
                "length",
                "density",
                "water_quota",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                "water",
                "electricity",
                "gas",
                "water_well",
                "car_door",
                "asphalt",
                "caretaker_house",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "building_status",
            "house_square",
            "yard",
            "price",
            "price_square",
            "bill_status",
            "length",
            "density",
            "water_quota",
            "video_door_phone",
            "janitor",
            "water",
            "electricity",
            "gas",
            "water_well",
            "car_door",
            "asphalt",
            "caretaker_house",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "house_square",
            "price",
            "price_square",
            "description",
            "image1",
            "image2",
            "image3",
        }


class RentBagh(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "deposit",
                "rent",
                "bill_status",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "category",
                "yard",
                "length",
                "eslahi",
                "water_quota",
                "fance",
                "agricultural_Type",
                "tree_ages",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                "water",
                "electricity",
                "gas",
                "water_well",
                "car_door",
                "asphalt",
                "caretaker_house",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "eslahi",
            "fance",
            "urban_area_number",
            "city",
            "address", "description",
            "house_square",
            "yard",
            "deposit",
            "rent",
            "bill_status",
            "length",
            "agricultural_Type",
            "tree_ages",
            "water_quota",
            "building_status",
            "swimming_pool",
            "video_door_phone",
            "janitor",
            "water",
            "electricity",
            "gas",
            "water_well",
            "car_door",
            "asphalt",
            "caretaker_house",
            "image1",
            "image2",
            "image3",
        )
        required = {
            "landlord_name",
            "title",
            "phone_number",
            "deposit",
            "rent",
            "description",
            "image1",
            "image2",
            "image3",
        }


class SellBuyBagh(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True


        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "price",
                "price_square",
                "bill_status",
                "eslahi",
                "fance",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "category",
                "yard",
                "length",
                "density",
                "water_quota",
                "agricultural_Type",
                "tree_ages",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                "water",
                "electricity",
                "gas",
                "water_well",
                "car_door",
                "asphalt",
                "caretaker_house",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "eslahi",
            "fance",
            "urban_area_number",
            "city",
            "address", "description",
            "house_square",
            "yard",
            "price",
            "price_square",
            "bill_status",
            "length",
            "agricultural_Type",
            "tree_ages",
            "water_quota",
            "building_status",
            "swimming_pool",
            "video_door_phone",
            "janitor",
            "water",
            "electricity",
            "gas",
            "water_well",
            "car_door",
            "asphalt",
            "caretaker_house",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "price",
            "price_square",
            "description",
            "image1",
            "image2",
            "image3",
        }


class RentAnbar(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "deposit",
                "rent",
                "bill_status",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "category",
                "yard",
                "length",
                "eslahi",
                "water_quota",
                "fance",
                "agricultural_Type",
                "tree_ages",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                "water",
                "electricity",
                "gas",
                "water_well",
                "car_door",
                "asphalt",
                "caretaker_house",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "urban_area_number",
            "year_of_construction",
            "room_number",
            "house_square",
            "deposit",
            "rent",
            "building_status",
            "parking",
            "elevator",
            "janitor",
            "water",
            "electricity",
            "gas",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "deposit",
            "rent",
            "description",
            "image1",
            "image2",
            "image3",
        }


class SellBuyAnbar(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "price",
                "price_square",
                "bill_status",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "category",
                "yard",
                "length",
                "eslahi",
                "water_quota",
                "fance",
                "agricultural_Type",
                "tree_ages",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                "water",
                "electricity",
                "gas",
                "water_well",
                "car_door",
                "asphalt",
                "caretaker_house",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "urban_area_number",
            "year_of_construction",
            "room_number",
            "house_square",
            "price",
            "price_square",
            "building_status",
            "parking",
            "elevator",
            "janitor",
            "water",
            "electricity",
            "gas",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "price",
            "price_square",
            "description",
            "image1",
            "image2",
            "image3",
        }


class RentSole(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "deposit",
                "rent",
                "bill_status",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "category",
                "yard",
                "length",
                "eslahi",
                "water_quota",
                "fance",
                "agricultural_Type",
                "tree_ages",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                "water",
                "electricity",
                "gas",
                "water_well",
                "car_door",
                "asphalt",
                "caretaker_house",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "urban_area_number",
            "year_of_construction",
            "house_square",
            "deposit",
            "rent",
            "bill_status",
            "building_status",
            "water",
            "electricity",
            "gas",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "deposit",
            "rent",
            "description",
            "image1",
            "image2",
            "image3",
        }


class SellBuySole(ModelForm, GenericImageSize):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
           Fieldset('اطلاعات مالک',
                    'landlord_name', 'phone_number',
                ),
           Fieldset(
               'اطلاعات ملک',
               'title',
                "price",
                "price_square",
                "bill_status",
                "description",
                "year_of_construction",
                "room_number",
                "house_square",
                "telephone_lines",
                "floor_number",
                "exposure_direction",
                "toilet_type",
                "building_view",
                "cabinet_type",
                "building_status",
                "flooring_type",
                "floors",
                "blocks_per_floor",
                "category",
                "yard",
                "length",
                "eslahi",
                "water_quota",
                "fance",
                "agricultural_Type",
                "tree_ages",
               ),

           Fieldset('اطلاعات ادرس',
                "quarter",
                "street",
                "plak",
                "address",
                "urban_area_number",
                "city",
                ),
           Fieldset('تجهیزات و امکانات ملک',
                 "parking",
                 "elevator",
                 "depot",
                 "sauna",
                 "jacuzzi",
                 "swimming_pool",
                 "balcony",
                 "kitchen",
                 "lobby",
                 "video_door_phone",
                 "remote",
                 "table_gas",
                "janitor",
                "water",
                "electricity",
                "gas",
                "water_well",
                "car_door",
                "asphalt",
                "caretaker_house",
                ),
           Fieldset('تصاویر',
                    "image1",
                    "image2",
                    "image3",
                ),
        )
        self.helper.layout.append(Submit('save', 'ثبت اگهی', css_class="btn btn-success btn-block"))

    class Meta:
        model = Advertisement
        fields = (
            "landlord_name",
            "title",
            "phone_number",
            "quarter",
            "street",
            "plak",
            "address", "description",
            "urban_area_number",
            "year_of_construction",
            "house_square",
            "price",
            "price_square",
            "bill_status",
            "building_status",
            "water",
            "electricity",
            "gas",
            "image1",
            "image2",
            "image3",
        )

        required = {
            "landlord_name",
            "title",
            "phone_number",
            "price",
            "price_square",
            "description",
            "image1",
            "image2",
            "image3",
        }
