
from django.forms import ModelForm
from .models import Advertisement


class RentApartment(ModelForm):

    class Meta:
        model = Advertisement
        fields = (
            "title",
            "phone_number",
            "address",
            "year_of_construction",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "floor_number",
            "exposure_direction",
            "deposit",
            "rent",
            "toilet_type",
            "building_view",
            "cabinet_type",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "sauna",
            "jacuzzi",
            "swimming_pool",
            "balcony",
            "kitchen",
            "lobby",
            "video_door_phone",
            "remote",
            "table_gas",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            "image1",
            "image2",
            "image3",
        )


class SellApartment(ModelForm):
    class Meta:
        model = Advertisement
        fields = (
            "title",
            "phone_number",
            "address",
            "year_of_construction",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "price",
            "price_square",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "exposure_direction",
            "bill_status",
            "density",
            "toilet_type",
            "building_view",
            "cabinet_type",
            "parking",
            "elevator",
            "depot",
            "sauna",
            "jacuzzi",
            "swimming_pool",
            "balcony",
            "kitchen",
            "lobby",
            "video_door_phone",
            "remote",
            "table_gas",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            )


class RentEdari(ModelForm):
    class Meta:
        model = Advertisement
        fields = (
            "title",
            "phone_number",
            "address",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "exposure_direction",
            "deposit",
            "rent",
            "toilet_type",
            "telephone_lines",
            "building_view",
            "cabinet_type",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "video_door_phone",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
        )


class SellEdari(ModelForm):
    class Meta:
        model = Advertisement
        fields = (
            "title",
            "phone_number",
            "address",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "price",
            "price_square",
            "exposure_direction",
            "toilet_type",
            "telephone_lines",
            "building_view",
            "cabinet_type",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "video_door_phone",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
        )


class RentColangi(ModelForm):
    class Meta:
        model = Advertisement
        fields = (
            "title",
            "phone_number",
            "address",
            "year_of_construction",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "yard",
            "exposure_direction",
            "deposit",
            "rent",
            "toilet_type",
            "building_view",
            "building_status",
            "cabinet_type",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "video_door_phone",
            "remote",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            )


class SellColangi(ModelForm):
    class Meta:
        model = Advertisement
        fields = (
            "title",
            "phone_number",
            "address",
            "year_of_construction",
            "room_number",
            "house_square",
            "urban_area_number",
            "city",
            "floor_number",
            "floors",
            "blocks_per_floor",
            "yard",
            "exposure_direction",
            "price",
            "price_square",
            "toilet_type",
            "building_view",
            "building_status",
            "cabinet_type",
            "flooring_type",
            "parking",
            "elevator",
            "depot",
            "video_door_phone",
            "remote",
            "water_cooler",
            "air_conditioners",
            "chiller",
            "duct_split",
            "package",
            "radiant",
            "heater",
            "floor_heating",
            )
