# Generated by Django 2.0 on 2019-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.PositiveIntegerField(default=71294),
        ),
    ]
