# Generated by Django 2.0 on 2019-08-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20190729_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.PositiveIntegerField(default=59255),
        ),
    ]
