# Generated by Django 2.0 on 2019-08-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20190805_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.PositiveIntegerField(default=86059),
        ),
    ]
