# Generated by Django 2.0 on 2019-08-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='commission_rate',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
