# Generated by Django 2.0 on 2019-08-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0004_auto_20190813_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='about_me',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='معرفی'),
        ),
    ]
