# Generated by Django 2.0 on 2019-08-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0005_consultant_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='name',
        ),
        migrations.AlterField(
            model_name='consultant',
            name='popularity',
            field=models.CharField(choices=[('1', '0'), ('2', '1'), ('3', '2'), ('4', '3'), ('5', '4')], default='5', max_length=1, verbose_name='محبوبیت'),
        ),
    ]
