# Generated by Django 2.0 on 2019-08-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0006_auto_20190813_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='popularity',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=1, verbose_name='محبوبیت'),
        ),
    ]
