# Generated by Django 2.0 on 2019-08-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0007_auto_20190813_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='long_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='معرفی جامع'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='about_me',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرفی'),
        ),
    ]
