# Generated by Django 2.0 on 2019-08-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0008_auto_20190813_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='long_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='معرفی جامع'),
        ),
    ]
