# Generated by Django 2.0 on 2019-08-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0009_auto_20190814_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='long_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='معرفی جامع'),
        ),
    ]
