# Generated by Django 2.0 on 2019-08-20 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0011_auto_20190815_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='commission_rate',
        ),
        migrations.AddField(
            model_name='consultant',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='agency_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام آژانس'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='agency_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09226255415'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره ثابت آزانس'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='arabi',
            field=models.BooleanField(default=False, verbose_name='اشنا به زبان عربی'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='degree',
            field=models.CharField(choices=[('1', 'زیر دیپلم'), ('2', 'دیپلم'), ('3', 'لیسانس'), ('4', 'کارشناسی ارشد'), ('5', 'دکترا')], default='1', max_length=1, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='english',
            field=models.BooleanField(default=False, verbose_name='اشنا به زبان انگلیسی'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='french',
            field=models.BooleanField(default=False, verbose_name='اشنا به زبان فراسنه'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='germany',
            field=models.BooleanField(default=False, verbose_name='اشنا به زبان المانی'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='job_experience',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='سابقه کار'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='kordi',
            field=models.BooleanField(default=False, verbose_name='اشنا به زبان کردی'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='russion',
            field=models.BooleanField(default=False, verbose_name='اشنا به زبان روسی'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='usage',
            field=models.CharField(choices=[('1', 'متقاضی ملک یا مالکم'), ('2', 'مشاور املاکم'), ('3', 'در حوزه مشاغل ساختمانی تخصص دارم')], default='1', max_length=1, verbose_name='مورد استفاده'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09226255415'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره موبایل'),
        ),
    ]
