# Generated by Django 2.0 on 2019-08-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0013_auto_20190823_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='degree',
            field=models.CharField(choices=[('1', 'زیر دیپلم'), ('2', 'دیپلم'), ('3', 'لیسانس'), ('4', 'کارشناسی ارشد'), ('5', 'دکترا')], max_length=1, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='usage',
            field=models.CharField(choices=[('1', 'متقاضی ملک یا مالکم'), ('2', 'مشاور املاکم'), ('3', 'در حوزه مشاغل ساختمانی تخصص دارم')], max_length=1, verbose_name='مورد استفاده'),
        ),
    ]
