# Generated by Django 2.0 on 2019-08-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0015_auto_20190823_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='agencies',
            field=models.BooleanField(default=True),
        ),
    ]
