# Generated by Django 2.0 on 2019-08-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0016_consultant_agencies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='agencies',
            new_name='consultant',
        ),
    ]
