# Generated by Django 2.0 on 2019-08-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0017_auto_20190829_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='consultant',
            field=models.BooleanField(default=False),
        ),
    ]
