# Generated by Django 2.2.3 on 2019-07-13 07:15

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190713_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_path)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Consultant')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_path)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Advertisement')),
            ],
        ),
    ]
