# Generated by Django 2.0 on 2019-08-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='favorites',
            field=models.ManyToManyField(to='advertisement.Advertisement'),
        ),
    ]
