# Generated by Django 2.0 on 2019-07-29 08:55

import advertisement.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اگهی')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09226255415'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='موبایل')),
                ('urban_area_number', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], max_length=2, null=True, verbose_name='منطقه')),
                ('city', models.CharField(blank=True, choices=[('1', 'تهران')], max_length=1, null=True, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='ادزس')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین اپدیت')),
                ('year_of_construction', models.CharField(blank=True, choices=[('1', '1398'), ('2', '1397'), ('3', '1396'), ('4', '1395'), ('5', '1394'), ('6', '1393'), ('7', '1392'), ('8', '1391'), ('9', '1390'), ('10', '1389'), ('11', '1387'), ('12', '1386'), ('13', '1385'), ('14', '1384'), ('15', '1383'), ('16', '1382'), ('17', '1381'), ('18', '1380'), ('19', '1379'), ('20', '1378'), ('21', '1377'), ('22', '1376'), ('23', '1375'), ('24', '1374'), ('25', '1373'), ('26', '1372'), ('27', '1371'), ('28', '1370')], max_length=2, null=True, verbose_name='سال ساخت')),
                ('room_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد اتاف')),
                ('house_square', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='متراژ')),
                ('category', models.CharField(blank=True, choices=[('0', 'خرید اپارتمان'), ('1', 'فروش اپارتمان'), ('2', 'رهن و اجاره اپارتمان'), ('3', 'خرید اداری'), ('4', 'فروش اداری'), ('5', 'رهن و اجاره اداری'), ('6', 'خرید کلنگی'), ('7', 'فروش کلنگی'), ('8', 'رهن و اجاره کلنگی'), ('9', 'خرید سوییت'), ('10', 'فروش سوییت'), ('11', 'رهن و اجاره سوییت'), ('12', 'خرید ویلا'), ('13', 'فروش ویلا'), ('14', 'رهن و اجاره ویلا'), ('15', 'خرید تجاری'), ('16', 'فروش تجاری'), ('17', 'رهن و اجاره تجاری'), ('18', 'خرید زمین'), ('19', 'فروش زمین'), ('20', 'رهن و اجاره زمین'), ('21', 'خرید باغ'), ('22', 'فروش باغ'), ('23', 'رهن و اجاره باغ'), ('24', 'خرید انبار'), ('25', 'فروش انبار'), ('26', 'رهن و اجاره انبار'), ('27', 'خرید سوله'), ('28', 'فروش سوله'), ('29', 'رهن و اجاره سوله')], max_length=2, null=True, verbose_name='دسته')),
                ('published', models.BooleanField(default=False, verbose_name='منتشرشده')),
                ('publish_review', models.CharField(blank=True, max_length=600, null=True, verbose_name='نظر منتشرکننده')),
                ('special', models.BooleanField(default=False, verbose_name='اگهی ویژه')),
                ('popularity', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True, verbose_name='محبوبیت')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('price_square', models.IntegerField(blank=True, null=True, verbose_name='قیمت متر مربع')),
                ('floor_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شماره طبقه')),
                ('floors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد طبقات')),
                ('blocks_per_floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد واحد هر طبقه')),
                ('yard', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='متراژ حیاط')),
                ('exposure_direction', models.CharField(blank=True, choices=[('0', 'شمالی'), ('1', 'جنوبی'), ('2', 'شرقی'), ('3', 'غربی'), ('4', 'تمام جهات')], max_length=1, null=True, verbose_name='جهت نوردهی')),
                ('deposit', models.IntegerField(blank=True, null=True, verbose_name='رهن')),
                ('rent', models.IntegerField(blank=True, null=True, verbose_name='اجاره')),
                ('bill_status', models.CharField(blank=True, choices=[('0', 'شخصی'), ('1', 'مسکونی'), ('2', 'اداری'), ('3', 'تجاری'), ('4', 'صنعتی'), ('5', 'تجاری صنعتی'), ('6', 'قولنامه ای'), ('7', 'تعاونی'), ('8', 'اوقافی'), ('9', 'سرقفلی'), ('10', 'بنیادی'), ('11', 'وکالتی'), ('12', 'مبابعه نامه'), ('13', 'صلح نامه ای'), ('14', 'بنچاق'), ('15', 'زمین شهری'), ('16', 'منگوله دار'), ('17', 'دست اول'), ('18', 'قراردادی'), ('19', 'در دست اقدام'), ('20', 'اماده محضر'), ('21', 'باغچه'), ('22', 'کشاورزی'), ('23', 'مشاع'), ('24', 'شهرداری'), ('25', 'بیت رهبری'), ('26', 'اعیان'), ('27', 'صنایع دفاع'), ('28', 'کارگاهی'), ('29', 'اموزشی'), ('30', 'سازمانی'), ('31', 'ستاد اجرایی'), ('32', 'برگه حاکم')], max_length=2, null=True, verbose_name='وضعیت سند')),
                ('density', models.IntegerField(blank=True, null=True, verbose_name='تراکم')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='طول بر')),
                ('agricultural_Type', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوع کاشت')),
                ('tree_ages', models.IntegerField(blank=True, null=True, verbose_name='عمر درختان')),
                ('water_quota', models.IntegerField(blank=True, null=True, verbose_name='سهمیه اب')),
                ('toilet_type', models.CharField(blank=True, choices=[('0', 'ایرانی'), ('1', 'فرنگی'), ('2', 'هردو')], max_length=1, null=True, verbose_name='نوع توالت')),
                ('telephone_lines', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد خط تلفن')),
                ('building_view', models.CharField(blank=True, choices=[('0', 'سنگ'), ('1', 'ترکیبی'), ('2', 'اجر نما'), ('3', 'کامپوزیت'), ('4', 'سیمان'), ('5', 'سیمان سفید'), ('6', 'سیمان رنگی'), ('7', 'گرانیت'), ('8', 'اجر سه سانت'), ('9', 'اجر سفال'), ('10', 'اجر گزی'), ('11', 'سنگ و شیشه'), ('12', 'شیشه رفرکس'), ('13', 'شیشه سکوریت'), ('14', 'الومینیوم'), ('15', 'تراورنن'), ('16', 'سرامیک'), ('17', 'چوب'), ('18', 'کنتکس'), ('19', 'رومالین'), ('20', 'الویایل'), ('21', 'گرالولیت')], max_length=2, null=True, verbose_name='نما ساختمان')),
                ('building_status', models.CharField(blank=True, choices=[('0', 'تخلیه'), ('1', 'اجاره'), ('2', 'سکونت مالک'), ('3', 'واگذار شده'), ('4', 'در حال ساخت')], max_length=1, null=True, verbose_name='وضعیت ملک')),
                ('cabinet_type', models.CharField(blank=True, choices=[('0', 'ندارد'), ('1', 'ناشمخص'), ('2', 'به انتخاب'), ('3', 'ام دی اف'), ('4', 'مایگلاس'), ('5', 'فلزی'), ('6', 'تمام چوب'), ('7', 'اچ دی اف'), ('8', 'ملامینه'), ('9', 'بلی وود'), ('10', 'پی وی سی'), ('11', 'نیوپان'), ('12', 'چوبی فلزی'), ('13', 'سنگ'), ('14', 'فرومیکا'), ('15', 'فایبرگلاس')], max_length=2, null=True, verbose_name='نوع کابینت')),
                ('flooring_type', models.CharField(blank=True, choices=[('0', 'سرامیک'), ('1', 'موازیک'), ('2', 'پارکت')], max_length=1, null=True, verbose_name='کفپوش')),
                ('parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('elevator', models.BooleanField(default=False, verbose_name='اسانسور')),
                ('depot', models.BooleanField(default=False, verbose_name='انباری')),
                ('sauna', models.BooleanField(default=False, verbose_name='سونا')),
                ('jacuzzi', models.BooleanField(default=False, verbose_name='جکوزی')),
                ('swimming_pool', models.BooleanField(default=False, verbose_name='استخر')),
                ('balcony', models.BooleanField(default=False, verbose_name='بالکون')),
                ('kitchen', models.BooleanField(default=False, verbose_name='اشپزخانه')),
                ('lobby', models.BooleanField(default=False, verbose_name='لابی')),
                ('video_door_phone', models.BooleanField(default=False, verbose_name='ایفون تصویری')),
                ('remote', models.BooleanField(default=False, verbose_name='ریموت')),
                ('janitor', models.BooleanField(default=False, verbose_name='سرایدار')),
                ('table_gas', models.BooleanField(default=False, verbose_name='گاز رو میزی')),
                ('water_cooler', models.BooleanField(default=False, verbose_name='کولر ابی')),
                ('air_conditioners', models.BooleanField(default=False, verbose_name='کولر گازی')),
                ('chiller', models.BooleanField(default=False, verbose_name='چیلر')),
                ('duct_split', models.BooleanField(default=False, verbose_name='داکت اسپیلیت')),
                ('package', models.BooleanField(default=False, verbose_name='پکیج')),
                ('radiant', models.BooleanField(default=False, verbose_name='شوفاژ')),
                ('heater', models.BooleanField(default=False, verbose_name='بخاری')),
                ('floor_heating', models.BooleanField(default=False, verbose_name='گرمایش از کف')),
                ('water', models.BooleanField(default=False, verbose_name='اب')),
                ('electricity', models.BooleanField(default=False, verbose_name='برق')),
                ('gas', models.BooleanField(default=False, verbose_name='گاز')),
                ('water_well', models.BooleanField(default=False, verbose_name='چاه اب')),
                ('car_door', models.BooleanField(default=False, verbose_name='درب ماشین رو')),
                ('asphalt', models.BooleanField(default=False, verbose_name='جاده اسفالت')),
                ('caretaker_house', models.BooleanField(default=False, verbose_name='خانه سرایدار')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=advertisement.models.get_image_path, verbose_name='تصویر شماره 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=advertisement.models.get_image_path, verbose_name='تصویر شماره 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=advertisement.models.get_image_path, verbose_name='تصویر شماره 3')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('consultants_number_allowed', models.SmallIntegerField(default=10, verbose_name='تعداد مشاورین مجاز برای دریافت اگهی')),
                ('allowed_capture_days', models.PositiveSmallIntegerField(default=10, verbose_name='روزهای مجاز داشتن اگهی')),
                ('allowed_ad_days', models.PositiveSmallIntegerField(default=5, verbose_name='روزهای مجاز نمایش اگهی')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.ConfigAdvertisement'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
