# Generated by Django 2.2.3 on 2019-07-17 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='agricultural_Type',
            field=models.CharField(max_length=200, null=True, verbose_name='نوع کاشت'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='air_conditioners',
            field=models.BooleanField(default=False, verbose_name='کولر گازی'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='asphalt',
            field=models.BooleanField(default=False, verbose_name='جاده اسفالت'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='balcony',
            field=models.BooleanField(default=False, verbose_name='بالکون'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='bill_status',
            field=models.CharField(choices=[('0', 'شخصی'), ('1', 'مسکونی'), ('2', 'اداری'), ('3', 'تجاری'), ('4', 'صنعتی'), ('5', 'تجاری صنعتی'), ('6', 'قولنامه ای'), ('7', 'تعاونی'), ('8', 'اوقافی'), ('9', 'سرقفلی'), ('10', 'بنیادی'), ('11', 'وکالتی'), ('12', 'مبابعه نامه'), ('13', 'صلح نامه ای'), ('14', 'بنچاق'), ('15', 'زمین شهری'), ('16', 'منگوله دار'), ('17', 'دست اول'), ('18', 'قراردادی'), ('19', 'در دست اقدام'), ('20', 'اماده محضر'), ('21', 'باغچه'), ('22', 'کشاورزی'), ('23', 'مشاع'), ('24', 'شهرداری'), ('25', 'بیت رهبری'), ('26', 'اعیان'), ('27', 'صنایع دفاع'), ('28', 'کارگاهی'), ('29', 'اموزشی'), ('30', 'سازمانی'), ('31', 'ستاد اجرایی'), ('32', 'برگه حاکم')], max_length=2, null=True, verbose_name='وضعیت سند'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='blocks_per_floor',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='تعداد واحد هر طبقه'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='building_status',
            field=models.CharField(choices=[('0', 'تخلیه'), ('1', 'اجاره'), ('2', 'سکونت مالک'), ('3', 'واگذار شده'), ('4', 'در حال ساخت')], max_length=1, null=True, verbose_name='وضعیت ملک'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='building_view',
            field=models.CharField(choices=[('0', 'سنگ'), ('1', 'ترکیبی'), ('2', 'اجر نما'), ('3', 'کامپوزیت'), ('4', 'سیمان'), ('5', 'سیمان سفید'), ('6', 'سیمان رنگی'), ('7', 'گرانیت'), ('8', 'اجر سه سانت'), ('9', 'اجر سفال'), ('10', 'اجر گزی'), ('11', 'سنگ و شیشه'), ('12', 'شیشه رفرکس'), ('13', 'شیشه سکوریت'), ('14', 'الومینیوم'), ('15', 'تراورنن'), ('16', 'سرامیک'), ('17', 'چوب'), ('18', 'کنتکس'), ('19', 'رومالین'), ('20', 'الویایل'), ('21', 'گرالولیت')], max_length=2, null=True, verbose_name='نما ساختمان'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='cabinet_type',
            field=models.CharField(choices=[('0', 'ندارد'), ('1', 'ناشمخص'), ('2', 'به انتخاب'), ('3', 'ام دی اف'), ('4', 'مایگلاس'), ('5', 'فلزی'), ('6', 'تمام چوب'), ('7', 'اچ دی اف'), ('8', 'ملامینه'), ('9', 'بلی وود'), ('10', 'پی وی سی'), ('11', 'نیوپان'), ('12', 'چوبی فلزی'), ('13', 'سنگ'), ('14', 'فرومیکا'), ('15', 'فایبرگلاس')], max_length=2, null=True, verbose_name='نوع کابینت'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='car_door',
            field=models.BooleanField(default=False, verbose_name='درب ماشین رو'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='caretaker_house',
            field=models.BooleanField(default=False, verbose_name='خانه سرایدار'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='chiller',
            field=models.BooleanField(default=False, verbose_name='چیلر'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='density',
            field=models.IntegerField(null=True, verbose_name='تراکم'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='deposit',
            field=models.IntegerField(null=True, verbose_name='رهن'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='depot',
            field=models.BooleanField(default=False, verbose_name='انباری'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='duct_split',
            field=models.BooleanField(default=False, verbose_name='داکت اسپیلیت'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='electricity',
            field=models.BooleanField(default=False, verbose_name='برق'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='اسانسور'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='exposure_direction',
            field=models.CharField(choices=[('0', 'شمالی'), ('1', 'جنوبی'), ('2', 'شرقی'), ('3', 'غربی'), ('4', 'تمام جهات')], max_length=1, null=True, verbose_name='جهت نوردهی'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='floor_heating',
            field=models.BooleanField(default=False, verbose_name='گرمایش از کف'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='floor_number',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='شماره طبقه'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='flooring_type',
            field=models.CharField(choices=[('0', 'سرامیک'), ('1', 'موازیک'), ('2', 'پارکت')], max_length=1, null=True, verbose_name='کفپوش'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='floors',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='تعداد طبقات'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='gas',
            field=models.BooleanField(default=False, verbose_name='گاز'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='heater',
            field=models.BooleanField(default=False, verbose_name='بخاری'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='jacuzzi',
            field=models.BooleanField(default=False, verbose_name='جکوزی'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='janitor',
            field=models.BooleanField(default=False, verbose_name='سرایدار'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='kitchen',
            field=models.BooleanField(default=False, verbose_name='اشپزخانه'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='length',
            field=models.IntegerField(null=True, verbose_name='طول بر'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='lobby',
            field=models.BooleanField(default=False, verbose_name='لابی'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='package',
            field=models.BooleanField(default=False, verbose_name='پکیج'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(null=True, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price_square',
            field=models.IntegerField(null=True, verbose_name='قیمت متر مربع'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='radiant',
            field=models.BooleanField(default=False, verbose_name='شوفاژ'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='ریموت'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='rent',
            field=models.IntegerField(null=True, verbose_name='اجاره'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='sauna',
            field=models.BooleanField(default=False, verbose_name='سونا'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='swimming_pool',
            field=models.BooleanField(default=False, verbose_name='استخر'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='table_gas',
            field=models.BooleanField(default=False, verbose_name='گاز رو میزی'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='telephone_lines',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='تعداد خط تلفن'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='toilet_type',
            field=models.CharField(choices=[('0', 'ایرانی'), ('1', 'فرنگی'), ('2', 'هردو')], max_length=1, null=True, verbose_name='نوع توالت'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='tree_ages',
            field=models.IntegerField(null=True, verbose_name='عمر درختان'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video_door_phone',
            field=models.BooleanField(default=False, verbose_name='ایفون تصویری'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='water',
            field=models.BooleanField(default=False, verbose_name='اب'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='water_cooler',
            field=models.BooleanField(default=False, verbose_name='کولر ابی'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='water_quota',
            field=models.IntegerField(null=True, verbose_name='سهمیه اب'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='water_well',
            field=models.BooleanField(default=False, verbose_name='چاه اب'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='yard',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='متراژ حیاط'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='address',
            field=models.CharField(max_length=300, null=True, verbose_name='ادزس'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='allowed_ad_days',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='روزهای مجاز نمایش اگهی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='allowed_capture_days',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='روزهای مجاز داشتن اگهی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('0', 'اپارتمان'), ('1', 'مسکونی'), ('2', 'اداری'), ('3', 'کلنگی'), ('3', 'سوییت'), ('3', 'ویلا'), ('3', 'تجاری'), ('3', 'زمین'), ('3', 'باغ')], max_length=1, null=True, verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.CharField(choices=[('1', 'Tehran')], max_length=1, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='consultants_number_allowed',
            field=models.SmallIntegerField(default=10, verbose_name='تعداد مشاورین مجاز برای دریافت اگهی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='house_square',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09226255415'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='popularity',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True, verbose_name='محبوبیت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='publish_review',
            field=models.CharField(max_length=600, null=True, verbose_name='نظر منتشرکننده'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='published',
            field=models.BooleanField(default=False, verbose_name='منتشرشده'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='room_number',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='تعداد اتاف'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='special',
            field=models.BooleanField(default=False, verbose_name='اگهی ویژه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان اگهی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین اپدیت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='urban_area_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], max_length=2, null=True, verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='year_of_construction',
            field=models.DateField(null=True, verbose_name='سال ساخت'),
        ),
    ]
