# Generated by Django 2.2.3 on 2019-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20190717_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ادزس'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='agricultural_Type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نوع کاشت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='bill_status',
            field=models.CharField(blank=True, choices=[('0', 'شخصی'), ('1', 'مسکونی'), ('2', 'اداری'), ('3', 'تجاری'), ('4', 'صنعتی'), ('5', 'تجاری صنعتی'), ('6', 'قولنامه ای'), ('7', 'تعاونی'), ('8', 'اوقافی'), ('9', 'سرقفلی'), ('10', 'بنیادی'), ('11', 'وکالتی'), ('12', 'مبابعه نامه'), ('13', 'صلح نامه ای'), ('14', 'بنچاق'), ('15', 'زمین شهری'), ('16', 'منگوله دار'), ('17', 'دست اول'), ('18', 'قراردادی'), ('19', 'در دست اقدام'), ('20', 'اماده محضر'), ('21', 'باغچه'), ('22', 'کشاورزی'), ('23', 'مشاع'), ('24', 'شهرداری'), ('25', 'بیت رهبری'), ('26', 'اعیان'), ('27', 'صنایع دفاع'), ('28', 'کارگاهی'), ('29', 'اموزشی'), ('30', 'سازمانی'), ('31', 'ستاد اجرایی'), ('32', 'برگه حاکم')], max_length=2, null=True, verbose_name='وضعیت سند'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='blocks_per_floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد واحد هر طبقه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='building_status',
            field=models.CharField(blank=True, choices=[('0', 'تخلیه'), ('1', 'اجاره'), ('2', 'سکونت مالک'), ('3', 'واگذار شده'), ('4', 'در حال ساخت')], max_length=1, null=True, verbose_name='وضعیت ملک'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='building_view',
            field=models.CharField(blank=True, choices=[('0', 'سنگ'), ('1', 'ترکیبی'), ('2', 'اجر نما'), ('3', 'کامپوزیت'), ('4', 'سیمان'), ('5', 'سیمان سفید'), ('6', 'سیمان رنگی'), ('7', 'گرانیت'), ('8', 'اجر سه سانت'), ('9', 'اجر سفال'), ('10', 'اجر گزی'), ('11', 'سنگ و شیشه'), ('12', 'شیشه رفرکس'), ('13', 'شیشه سکوریت'), ('14', 'الومینیوم'), ('15', 'تراورنن'), ('16', 'سرامیک'), ('17', 'چوب'), ('18', 'کنتکس'), ('19', 'رومالین'), ('20', 'الویایل'), ('21', 'گرالولیت')], max_length=2, null=True, verbose_name='نما ساختمان'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='cabinet_type',
            field=models.CharField(blank=True, choices=[('0', 'ندارد'), ('1', 'ناشمخص'), ('2', 'به انتخاب'), ('3', 'ام دی اف'), ('4', 'مایگلاس'), ('5', 'فلزی'), ('6', 'تمام چوب'), ('7', 'اچ دی اف'), ('8', 'ملامینه'), ('9', 'بلی وود'), ('10', 'پی وی سی'), ('11', 'نیوپان'), ('12', 'چوبی فلزی'), ('13', 'سنگ'), ('14', 'فرومیکا'), ('15', 'فایبرگلاس')], max_length=2, null=True, verbose_name='نوع کابینت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'اپارتمان'), ('1', 'مسکونی'), ('2', 'اداری'), ('3', 'کلنگی'), ('3', 'سوییت'), ('3', 'ویلا'), ('3', 'تجاری'), ('3', 'زمین'), ('3', 'باغ')], max_length=1, null=True, verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.CharField(blank=True, choices=[('1', 'Tehran')], max_length=1, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='density',
            field=models.IntegerField(blank=True, null=True, verbose_name='تراکم'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='رهن'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='exposure_direction',
            field=models.CharField(blank=True, choices=[('0', 'شمالی'), ('1', 'جنوبی'), ('2', 'شرقی'), ('3', 'غربی'), ('4', 'تمام جهات')], max_length=1, null=True, verbose_name='جهت نوردهی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شماره طبقه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='flooring_type',
            field=models.CharField(blank=True, choices=[('0', 'سرامیک'), ('1', 'موازیک'), ('2', 'پارکت')], max_length=1, null=True, verbose_name='کفپوش'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد طبقات'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='house_square',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='طول بر'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='popularity',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True, verbose_name='محبوبیت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price_square',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت متر مربع'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='publish_review',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='نظر منتشرکننده'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='rent',
            field=models.IntegerField(blank=True, null=True, verbose_name='اجاره'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='room_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد اتاف'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='telephone_lines',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد خط تلفن'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='toilet_type',
            field=models.CharField(blank=True, choices=[('0', 'ایرانی'), ('1', 'فرنگی'), ('2', 'هردو')], max_length=1, null=True, verbose_name='نوع توالت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='tree_ages',
            field=models.IntegerField(blank=True, null=True, verbose_name='عمر درختان'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='urban_area_number',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], max_length=2, null=True, verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='water_quota',
            field=models.IntegerField(blank=True, null=True, verbose_name='سهمیه اب'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='yard',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='متراژ حیاط'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='year_of_construction',
            field=models.DateField(blank=True, null=True, verbose_name='سال ساخت'),
        ),
    ]
