# Generated by Django 2.0 on 2019-08-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20190805_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
    ]
