# Generated by Django 2.2.3 on 2019-07-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20190717_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'اپارتمان'), ('2', 'اداری'), ('3', 'کلنگی'), ('4', 'سوییت'), ('5', 'ویلا'), ('6', 'تجاری'), ('7', 'زمین'), ('8', 'باغ')], max_length=1, null=True, verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='year_of_construction',
            field=models.CharField(blank=True, choices=[('1', '1398'), ('2', '1397'), ('3', '1396'), ('4', '1395'), ('5', '1394'), ('6', '1393'), ('7', '1392'), ('8', '1391'), ('9', '1390'), ('10', '1389'), ('11', '1387'), ('12', '1386'), ('13', '1385'), ('14', '1384'), ('15', '1383'), ('16', '1382'), ('17', '1381'), ('18', '1380'), ('19', '1379'), ('20', '1378'), ('21', '1377'), ('22', '1376'), ('23', '1375'), ('24', '1374'), ('25', '1373'), ('26', '1372'), ('27', '1371'), ('28', '1370')], max_length=2, null=True, verbose_name='سال ساخت'),
        ),
    ]
