# Generated by Django 2.2.3 on 2019-07-22 06:51

import advertisement.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0004_auto_20190722_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=advertisement.models.get_image_path, verbose_name='...تصویر شماره 1'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=advertisement.models.get_image_path, verbose_name='...تصویر شماره 2'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=advertisement.models.get_image_path, verbose_name='...تصویر شماره 3'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='air_conditioners',
            field=models.BooleanField(default=False, verbose_name='...کولر گازی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='asphalt',
            field=models.BooleanField(default=False, verbose_name='...جاده اسفالت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='balcony',
            field=models.BooleanField(default=False, verbose_name='...بالکون'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='car_door',
            field=models.BooleanField(default=False, verbose_name='...درب ماشین رو'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='caretaker_house',
            field=models.BooleanField(default=False, verbose_name='...خانه سرایدار'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='chiller',
            field=models.BooleanField(default=False, verbose_name='...چیلر'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.CharField(blank=True, choices=[('1', 'تهران')], max_length=1, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='depot',
            field=models.BooleanField(default=False, verbose_name='...انباری'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='duct_split',
            field=models.BooleanField(default=False, verbose_name='...داکت اسپیلیت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='electricity',
            field=models.BooleanField(default=False, verbose_name='...برق'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='...اسانسور'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='floor_heating',
            field=models.BooleanField(default=False, verbose_name='...گرمایش از کف'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='gas',
            field=models.BooleanField(default=False, verbose_name='...گاز'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='heater',
            field=models.BooleanField(default=False, verbose_name='...بخاری'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='jacuzzi',
            field=models.BooleanField(default=False, verbose_name='...جکوزی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='janitor',
            field=models.BooleanField(default=False, verbose_name='...سرایدار'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='kitchen',
            field=models.BooleanField(default=False, verbose_name='...اشپزخانه'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='lobby',
            field=models.BooleanField(default=False, verbose_name='...لابی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='package',
            field=models.BooleanField(default=False, verbose_name='...پکیج'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='...پارکینگ'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='radiant',
            field=models.BooleanField(default=False, verbose_name='...شوفاژ'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='...ریموت'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='sauna',
            field=models.BooleanField(default=False, verbose_name='...سونا'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='swimming_pool',
            field=models.BooleanField(default=False, verbose_name='...استخر'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='table_gas',
            field=models.BooleanField(default=False, verbose_name='...گاز رو میزی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video_door_phone',
            field=models.BooleanField(default=False, verbose_name='...ایفون تصویری'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='water',
            field=models.BooleanField(default=False, verbose_name='...اب'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='water_cooler',
            field=models.BooleanField(default=False, verbose_name='...کولر ابی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='water_well',
            field=models.BooleanField(default=False, verbose_name='...چاه اب'),
        ),
        migrations.DeleteModel(
            name='AdvertisementImage',
        ),
    ]
