# Generated by Django 2.2.3 on 2019-07-22 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_auto_20190722_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09226255415'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='موبایل'),
        ),
    ]
