# Generated by Django 2.0 on 2019-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_auto_20190926_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره طبقه'),
        ),
    ]
