# Generated by Django 2.2.3 on 2019-07-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_auto_20190722_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('consultants_number_allowed', models.SmallIntegerField(default=10, verbose_name='تعداد مشاورین مجاز برای دریافت اگهی')),
                ('allowed_capture_days', models.PositiveSmallIntegerField(default=10, verbose_name='روزهای مجاز داشتن اگهی')),
                ('allowed_ad_days', models.PositiveSmallIntegerField(default=5, verbose_name='روزهای مجاز نمایش اگهی')),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='allowed_ad_days',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='allowed_capture_days',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='consultants_number_allowed',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'خرید اپارتمان'), ('1', 'فروش اپارتمان'), ('2', 'رهن و اجاره اپارتمان'), ('3', 'خرید اداری'), ('4', 'فروش اداری'), ('5', 'رهن و اجاره اداری'), ('6', 'خرید کلنگی'), ('7', 'فروش کلنگی'), ('8', 'رهن و اجاره کلنگی'), ('9', 'خرید سوییت'), ('10', 'فروش سوییت'), ('11', 'رهن و اجاره سوییت'), ('12', 'خرید ویلا'), ('13', 'فروش ویلا'), ('14', 'رهن و اجاره ویلا'), ('15', 'خرید تجاری'), ('16', 'فروش تجاری'), ('17', 'رهن و اجاره تجاری'), ('18', 'خرید زمین'), ('19', 'فروش زمین'), ('20', 'رهن و اجاره زمین'), ('21', 'خرید باغ'), ('22', 'فروش باغ'), ('23', 'رهن و اجاره باغ'), ('24', 'خرید انبار'), ('25', 'فروش انبار'), ('26', 'رهن و اجاره انبار')], max_length=2, null=True, verbose_name='دسته'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.ConfigAdvertisement'),
        ),
    ]
