# Generated by Django 2.2.3 on 2019-07-27 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_auto_20190722_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'خرید اپارتمان'), ('1', 'فروش اپارتمان'), ('2', 'رهن و اجاره اپارتمان'), ('3', 'خرید اداری'), ('4', 'فروش اداری'), ('5', 'رهن و اجاره اداری'), ('6', 'خرید کلنگی'), ('7', 'فروش کلنگی'), ('8', 'رهن و اجاره کلنگی'), ('9', 'خرید سوییت'), ('10', 'فروش سوییت'), ('11', 'رهن و اجاره سوییت'), ('12', 'خرید ویلا'), ('13', 'فروش ویلا'), ('14', 'رهن و اجاره ویلا'), ('15', 'خرید تجاری'), ('16', 'فروش تجاری'), ('17', 'رهن و اجاره تجاری'), ('18', 'خرید زمین'), ('19', 'فروش زمین'), ('20', 'رهن و اجاره زمین'), ('21', 'خرید باغ'), ('22', 'فروش باغ'), ('23', 'رهن و اجاره باغ'), ('24', 'خرید انبار'), ('25', 'فروش انبار'), ('26', 'رهن و اجاره انبار'), ('27', 'خرید سوله'), ('28', 'فروش سوله'), ('29', 'رهن و اجاره سوله')], max_length=2, null=True, verbose_name='دسته'),
        ),
    ]
