# Generated by Django 2.0 on 2019-08-16 09:52

import agencies.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.BooleanField(default=False, verbose_name='کاربر ویژه')),
                ('skill', models.CharField(blank=True, max_length=100, null=True, verbose_name='تخصص')),
                ('urban_area_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], max_length=2, verbose_name='شماره منطقه')),
                ('address', models.CharField(max_length=300, verbose_name='ادرس')),
                ('city', models.CharField(choices=[('1', 'Tehran')], max_length=1, verbose_name='شهر')),
                ('popularity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=1, verbose_name='محبوبیت')),
                ('commission_rate', models.IntegerField(blank=True, null=True, verbose_name='نرخ کمیسیون')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت اکانت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='اخرین به روز رسانی')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09226255415'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفن')),
                ('about_me', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرفی')),
                ('long_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='معرفی جامع')),
                ('image', models.ImageField(blank=True, null=True, upload_to=agencies.models.get_image_path, verbose_name='تصویر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
