# Generated by Django 2.0 on 2019-08-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_auto_20190823_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencies',
            name='consultant',
            field=models.BooleanField(default=True),
        ),
    ]
