# Generated by Django 2.0 on 2019-08-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_agencies_consultant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencies',
            old_name='consultant',
            new_name='agencies',
        ),
    ]
