# Generated by Django 2.0 on 2019-08-17 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09226255415'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره موبایل'),
        ),
    ]
